name:  Create flutter build

on:
  # Runs this action when you push on master and development
  push:
    branches:
      - "main"
      - "development"
  pull_request:
    branches:
      - "development"


jobs:
  flutter_job:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest

    env:
      KEYSTORE_PATH: apps/AppWithWearable/android/app/upload-keystore.jks
      ASC_JSON_KEY: ${{ secrets.ASC_JSON_KEY }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD : ${{ secrets.APPLE_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      #Steps for Fastlane
      #1
      #Setup ruby version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'

      #2
      - name: Install Bundler
        run: gem install bundler

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-  

      #3
      - name: Install Fastlane
        run: bundle install

      # Setup the env
      - name: Setup Env
        run: cat .env.template > .env
        working-directory: apps/AppWithWearable

      # Build runner
      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: apps/AppWithWearable

      # Decoding jks file
      - name: Decode and write keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.SECRET_JKS }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_PATH

      - name: Install dependencies
        run: flutter pub get
        working-directory: apps/AppWithWearable

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '15.0.1'

      - name: Setup app store connect
        run: echo '${{ secrets.ASC_JSON_KEY }}' > apps/AppWithWearable/ios/fastlane/store.json

      - name: Install Pod
        run: pod install
        working-directory: apps/AppWithWearable/ios

      - name: Run Fastlane for iOS
        run: bundle exec fastlane beta --verbose
        working-directory: apps/AppWithWearable/ios
        env:
          MATCH_PASSWORD : ${{ secrets.MATCH_PASSWORD }}
          ASC_JSON_KEY: ${{ secrets.ASC_JSON_KEY }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          CI: true

